Adding Help to Alpha Release
mezerotm/cmv pull request #38
Opened 2017-03-04 14:48 UTC by hardnett

This is the help overlay to satisfy issue #22. 

Here are some examples of what it looks like:
![screen shot 2017-03-04 at 9 34 53 am](https://cloud.githubusercontent.com/assets/2136554/23579617/fc9ac884-00be-11e7-8c8e-5f5ffdcc3003.png)
![screen shot 2017-03-04 at 9 35 04 am](https://cloud.githubusercontent.com/assets/2136554/23579618/008fd2cc-00bf-11e7-8861-3f23f5c51795.png)
![screen shot 2017-03-04 at 9 35 18 am](https://cloud.githubusercontent.com/assets/2136554/23579619/02ac87ee-00bf-11e7-9f2e-a0d44d78cd35.png)

2017-03-04 21:41 UTC, mezerotm commented
## Code Comments

- We still have display.sidebar.help.js I suggest we either rename intro.js to better fit our naming convention or at least remove display.sidebar.help.js since that code is now deprecated.

- This is something I had thought of doing too (introducing third-party code) but I feared that it would lead down the road of 'unused code' and improper modularity I don't know how much of this code is bare minimum, but I hope we can look into maybe importing a CDN minified and then writing what we need in our code base. We already have the challenge of loading a lot of geo data and drawing it on a map I would dislike for a help feature to be the additional cause of a 5 second loading time.

- Here are some webstorm code inspections I ran on the file: [js.intro.js-03-04-17.zip](https://drive.google.com/open?id=0B-wZylPuiwuKcG5aWTVWdUtIM1k)
Here's the [tl;dr](https://en.wikipedia.org/wiki/Wikipedia:Too_long;_didn't_read)
         - you're using a lot of var's try using let's
         - you're redeclaring a lot of variables
         - you have many 'spelling mistakes' (this is stuff like combined words it considers "introjs" to be a                 spelling mistake)

_*These are just notes for the sake of documentation_

## Superficial Comments
### Tiny Things I Noticed

- The skip button is essentially useless since at any moment I can click anywhere on the screen and it will stop the presentation. On that same note, clicking anywhere on the screen skips the presentation, I've already skipped it twice by accident myself now. We need to make it so you can only skip by clicking the skip button. 
_(can be fixed at Line:54)_

- For steps 1 & 2 the step indicator is off screen. This is not a big issue to me, but i figured I would document it. 
_(can be fixed at Line:56)_

- Step 8 (education icon highlight): Implies there are more variable options after by stating "Press this icon to select a education variable, OR" this can be fixed by removing the OR

### Additional 'featured' Notes

- would be nice if when we get to step 2 (the first time it mentions variables) if we could instead of listing more variables, is instead open the variable up for them or force them to open it and show the steps of clicking a radio button and then going through the process of clicking submit. I imagine a more forceful tutorial where they cannot progress until they comply with the instructions. 

- I think we should stop calling them variables, in terms of when trying to explain it to the public. We can obviously still call them variables but I think variables doesn't sound friendly.

2017-03-04 21:42 UTC, mezerotm requested changes
## Code Comments

- We still have display.sidebar.help.js I suggest we either rename intro.js to better fit our naming convention or at least remove display.sidebar.help.js since that code is now deprecated.

- This is something I had thought of doing too (introducing third-party code) but I feared that it would lead down the road of 'unused code' and improper modularity I don't know how much of this code is bare minimum, but I hope we can look into maybe importing a CDN minified and then writing what we need in our code base. We already have the challenge of loading a lot of geo data and drawing it on a map I would dislike for a help feature to be the additional cause of a 5 second loading time.

- Here are some webstorm code inspections I ran on the file: [js.intro.js-03-04-17.zip](https://drive.google.com/open?id=0B-wZylPuiwuKcG5aWTVWdUtIM1k)
Here's the [tl;dr](https://en.wikipedia.org/wiki/Wikipedia:Too_long;_didn't_read)
         - you're using a lot of var's try using let's
         - you're redeclaring a lot of variables
         - you have many 'spelling mistakes' (this is stuff like combined words it considers "introjs" to be a                 spelling mistake)

_*These are just notes for the sake of documentation_

## Superficial Comments
### Tiny Things I Noticed

- The skip button is essentially useless since at any moment I can click anywhere on the screen and it will stop the presentation. On that same note, clicking anywhere on the screen skips the presentation, I've already skipped it twice by accident myself now. We need to make it so you can only skip by clicking the skip button. 
_(can be fixed at Line:54)_

- For steps 1 & 2 the step indicator is off screen. This is not a big issue to me, but i figured I would document it. 
_(can be fixed at Line:56)_

- Step 8 (education icon highlight): Implies there are more variable options after by stating "Press this icon to select a education variable, OR" this can be fixed by removing the OR

### Additional 'featured' Notes

- would be nice if when we get to step 2 (the first time it mentions variables) if we could instead of listing more variables, is instead open the variable up for them or force them to open it and show the steps of clicking a radio button and then going through the process of clicking submit. I imagine a more forceful tutorial where they cannot progress until they comply with the instructions. 

- I think we should stop calling them variables, in terms of when trying to explain it to the public. We can obviously still call them variables but I think variables doesn't sound friendly.

2017-03-05 02:56 UTC, hardnett commented
# Code Comments (Replies)
_We still have display.sidebar.help.js I suggest we either rename intro.js to better fit our naming convention or at least remove display.sidebar.help.js since that code is now deprecated._

- Yes, this code will be removed along with the placeholder code in index.html. This can be done after this merge since there is another merge of index.html in #37. 

_This is something I had thought of doing too (introducing third-party code) but I feared that it would lead down the road of 'unused code' and improper modularity I don't know how much of this code is bare minimum, but I hope we can look into maybe importing a CDN minified and then writing what we need in our code base. We already have the challenge of loading a lot of geo data and drawing it on a map I would dislike for a help feature to be the additional cause of a 5 second loading time._

- I am not sure why this is a concern. The intro.js file  is 61KB, and the 2 css files combined are 20KB. Thats 81 KB combined  that is loaded once. (the previous solution involved loading 2 PNG images that were 64KB+ combined each time the help-button was clicked). Minification would be a concern if this were a larger library; for example, JQuery unminified is > 200K and minified is hovering around 84K. Our total load time is 47ms and scripting time during loading is about 1s. There are about 20ms for rendering. So our total is barely over a 1s. This added module is probably 1-2 ms. Using 3rd party code like this is pretty standard on web apps: CitySDK, Google Maps, etc. The added time for us to build our own code to do this is an added dev time for non-core requirement. We also have access to the code for updates.

_Here are some webstorm code inspections I ran on the file: js.intro.js-03-04-17.zip_

- The webstorm code inspections are useful as a diagnostic, and would be more of an issue for the core of our app. I'd be interested in knowing what it gives us for our code and for the CItySDK code. Logan may be interested in that as well. Because of the minimal impact to our app, this is duly noted, but not a priority in my mind. Others may feel differently. 

# Superficial Comments
_The skip button is essentially useless since at any moment I can click anywhere on the screen and it will stop the presentation. On that same note, clicking anywhere on the screen skips the presentation, I've already skipped it twice by accident myself now. We need to make it so you can only skip by clicking the skip button.
(can be fixed at Line:54)_

- You can also exit the presentation by pressing ESC. Why is having multiple ways to escape a problem? We can hide the skip button as well. I am not sure what "line:54" references. Which file?

_For steps 1 & 2 the step indicator is off screen. This is not a big issue to me, but i figured I would document it.
(can be fixed at Line:56)_

- Yes, I noticed it as well. There was no quick fix for this. I suspect it will require changing the CSS they have for building the UI. All of their themes put the number in the upper-lefthand corner, and so changing their code to allow the position of the number to change like the position of the tooltip is a possibility, Or it may be that we pad our screen with a margin at the top of 20 or so pixels to ensure there is space (this may be easier and won't sacrifice much. But its not something for this PR to handle. 

_Step 8 (education icon highlight): Implies there are more variable options after by stating "Press this icon to select a education variable, OR" this can be fixed by removing the OR_

- Good Catch. No issue there.

# Additional 'featured' Notes

These are good points for discussion. Open an issue for each one and tag them as research. They can be for discussion in the Beta Release in my opinion because they do not impact the core functionality of the Alpha Release.

2017-03-05 03:26 UTC, mezerotm commented
_I am not sure why this is a concern. The intro.js file is 61KB, and the 2 css files combined are 20KB. Thats 81 KB combined that is loaded once. (the previous solution involved loading 2 PNG images that were 64KB+ combined each time the help-button was clicked). Minification would be a concern if this were a larger library; for example, JQuery unminified is > 200K and minified is hovering around 84K. Our total load time is 47ms and scripting time during loading is about 1s. There are about 20ms for rendering. So our total is barely over a 1s. This added module is probably 1-2 ms. Using 3rd party code like this is pretty standard on web apps: CitySDK, Google Maps, etc. The added time for us to build our own code to do this is an added dev time for non-core requirement. We also have access to the code for updates._

- File size is always just a concern to me, maybe it's a bad habit of myn but it's something I enjoy about programming. You do make a valid point my PNG's are worse than what you have introduced as a solution, forgive my hypocrisy.

_The webstorm code inspections are useful as a diagnostic, and would be more of an issue for the core of our app. I'd be interested in knowing what it gives us for our code and for the CItySDK code. Logan may be interested in that as well. Because of the minimal impact to our app, this is duly noted, but not a priority in my mind. Others may feel differently._ 

- Running these inspections is fairly easy I can run a report on anything you want that would be no problem. Anyone can runs these in fact as long as they have a product from intellij.

_You can also exit the presentation by pressing ESC. Why is having multiple ways to escape a problem? We can hide the skip button as well. I am not sure what "line:54" references. Which file?_

- Maybe you understood me wrong. I like the skip button and I have no issue having multiple ways of exiting the presentation I was just pointing out that I accidently excited the presentation to often. I was referring to[ js/intro.js#Line:54](https://github.com/mezerotm/cmv/blob/02d0afe9290c4a731cd88975ac38d4ecd3f1903e/js/intro.js#L54) &  [js/intro.js#56](https://github.com/mezerotm/cmv/blob/02d0afe9290c4a731cd88975ac38d4ecd3f1903e/js/intro.js#L56) these two are just boolean values so I was implying we switch them to false.

2017-03-05 04:42 UTC, hardnett commented
_You can also exit the presentation by pressing ESC. Why is having multiple ways to escape a problem? We can hide the skip button as well. I am not sure what "line:54" references. Which file?

Maybe you understood me wrong. I like the skip button and I have no issue having multiple ways of exiting the presentation I was just pointing out that I accidently excited the presentation to often. I was referring to js/intro.js#Line:54 & js/intro.js#56 these two are just boolean values so I was implying we switch them to false._

- Okay. I gotcha. In general, I do not like the idea of updating code in libraries because if we update the library in the future, then the same issue may still be there. I would suggest making a pull-request to the authors on their github about it. I think the easier solution for us is to use the "hiding" of the skip button. Frankly, I had not used the skip button at all when I was playing with it. Make an issue for it, and I'll fix it in another update. Its not hard to hide it.

2017-03-06 00:27 UTC, hardnett commented
@mezerotm are we good to go? Please approve if I can do this merge.

2017-03-06 03:21 UTC, mezerotm approved these changes

2017-03-06 14:01 UTC, merged